# Kong Gatewayのコンテナイメージを指定します。
image:
  # ユーザー指定のリポジトリを使用します。
  repository: ghcr.io/konosukeaida/kongbootcamp
  # 本番環境での不変性を保証するため、SHAダイジェスト付きのタグを指定します。
  tag: "1c3ee6c8830a50cf61c63d9eb97fb0d2fc7a6656"
  effectiveSemver: v3.10

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: 72ede01046.au.cp.konghq.com:443
  cluster_dp_labels: "type:docker-kubernetesOS"
  cluster_server_name: 72ede01046.au.cp.konghq.com
  cluster_telemetry_endpoint: 72ede01046.au.tp.konghq.com:443
  cluster_telemetry_server_name: 72ede01046.au.tp.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  router_flavor: expressions

ingressController:
  enabled: false
  installCRDs: false

resources:
  requests:
    cpu: 1
    memory: "2Gi"

manager:
  enabled: false